// Web后台与NCX客户端的rpc通信协议

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: client.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigInfo_AskConfigInfo_FullMethodName = "/protocol.ncx_client.ConfigInfo/AskConfigInfo"
)

// ConfigInfoClient is the client API for ConfigInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 配置信息服务
type ConfigInfoClient interface {
	// 获取配置信息
	AskConfigInfo(ctx context.Context, in *ConfigInfoReq, opts ...grpc.CallOption) (*ConfigInfoResp, error)
}

type configInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigInfoClient(cc grpc.ClientConnInterface) ConfigInfoClient {
	return &configInfoClient{cc}
}

func (c *configInfoClient) AskConfigInfo(ctx context.Context, in *ConfigInfoReq, opts ...grpc.CallOption) (*ConfigInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigInfoResp)
	err := c.cc.Invoke(ctx, ConfigInfo_AskConfigInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigInfoServer is the server API for ConfigInfo service.
// All implementations must embed UnimplementedConfigInfoServer
// for forward compatibility.
//
// 配置信息服务
type ConfigInfoServer interface {
	// 获取配置信息
	AskConfigInfo(context.Context, *ConfigInfoReq) (*ConfigInfoResp, error)
	mustEmbedUnimplementedConfigInfoServer()
}

// UnimplementedConfigInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigInfoServer struct{}

func (UnimplementedConfigInfoServer) AskConfigInfo(context.Context, *ConfigInfoReq) (*ConfigInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskConfigInfo not implemented")
}
func (UnimplementedConfigInfoServer) mustEmbedUnimplementedConfigInfoServer() {}
func (UnimplementedConfigInfoServer) testEmbeddedByValue()                    {}

// UnsafeConfigInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigInfoServer will
// result in compilation errors.
type UnsafeConfigInfoServer interface {
	mustEmbedUnimplementedConfigInfoServer()
}

func RegisterConfigInfoServer(s grpc.ServiceRegistrar, srv ConfigInfoServer) {
	// If the following call pancis, it indicates UnimplementedConfigInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigInfo_ServiceDesc, srv)
}

func _ConfigInfo_AskConfigInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigInfoServer).AskConfigInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigInfo_AskConfigInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigInfoServer).AskConfigInfo(ctx, req.(*ConfigInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigInfo_ServiceDesc is the grpc.ServiceDesc for ConfigInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ncx_client.ConfigInfo",
	HandlerType: (*ConfigInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskConfigInfo",
			Handler:    _ConfigInfo_AskConfigInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
